#pragma once

// 씬이름 정의
enum E_LEVEL { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_GAMEPLAY, LEVEL_TOOL, LEVEL_END };

// 레이어 이름 정의
enum E_TAYLAY
{
	LAY_NONE,
	LAY_BACKGROUND,
	LAY_CAMERA,
	LAY_PLAYER,
	LAY_OBJECT,
	LAY_END
};

static const wchar_t* STR_TAYLAY(E_TAYLAY lay)
{
	switch (lay)
	{
	case LAY_NONE:
		return L"LAY_NONE";
	case LAY_BACKGROUND:
		return L"LAY_BACKGROUND";
	case LAY_CAMERA:
		return L"LAY_CAMERA";
	case LAY_PLAYER:
		return L"LAY_PLAYER";
	case LAY_OBJECT:
		return L"LAY_OBJECT";
	case LAY_END:
		return L"LAY_END";
	default:
		return L"LAY";
	}
}

// 컴포넌트 프로토 이름 정의
enum E_TAYCOMPONENT
{
	COMPONENT_NONE,
	COMPONENT_VUFFER,
	COMPONENT_RECTBUFFER,
	COMPONENT_TRANSFORM,
	COMPONENT_RENDERER,
	COMPONENT_END,
};

static const wchar_t* STR_TAYCOM(E_TAYCOMPONENT com)
{
	switch (com)
	{
	case COMPONENT_VUFFER:
		return L"COMPONENT_VUFFER";
	case COMPONENT_RECTBUFFER:
		return L"COMPONENT_RECTBUFFER";
	case COMPONENT_TRANSFORM:
		return L"COMPONENT_TRANSFORM";
	case COMPONENT_RENDERER:
		return L"COMPONENT_RENDERER";
	default:
		return L"COMPONENT";
	}
}

// 게임오브젝트 프로토 이름 정의
enum E_TAYGAMEOBJECT
{
	GAMEOBJECT_NONE,
	GAMEOBJECT_BACKGROUND,
	GAMEOBJECT_CAMERA,
	GAMEOBJECT_PLAYER,
	GAMEOBJECT_END,
};

static const wchar_t* STR_TAYOBJ(E_TAYGAMEOBJECT obj)
{
	switch (obj)
	{
	case GAMEOBJECT_BACKGROUND:
		return L"GAMEOBJECT_BACKGROUND";
	case GAMEOBJECT_CAMERA:
		return L"GAMEOBJECT_CAMERA";
	case GAMEOBJECT_PLAYER:
		return L"GAMEOBJECT_PLAYER";
	default:
		return L"GAMEOBJECT";
	}
}

#define  TAGLAY STR_TAYLAY
#define  TAGCOM STR_TAYCOM
#define  TAGOBJ STR_TAYOBJ